# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Final Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
  # Pods for Final Project

end
